defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-youtube

url: "https://council.csie.ntu.edu.tw"
baseurl: "/44th"
