defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-youtube

include: ["/_data", "index.js"]
exclude: ["/.git"]
url: "https://council.csie.ntu.edu.tw"
baseurl: ""
